/** @type {import('tailwindcss').Config} */
export default {
    content: ['./src/**/*.{html,js,svelte,ts}'],
    theme: {
        extend: {
            colors: {
                LightModeBG: '#f5f5f5',
                DarkModeBG: '#18181b',
                LightModeTitleBarBG: '#e5e5e5',
                DarkModeTitleBarBG: '#09090b',
                LightModeTextInputBG: '#e5e5e5',
                DarkModeTextInputBG: '#27272a',
                LightModePrimBtn: '#e5e5e5',
                DarkModePrimBtn: '#e4e4e7',
                LightModePrimBtnHover: '#e5e5e5',
                DarkModePrimBtnHover: '#d4d4d8',
                LightModePrimBtnText: '#e5e5e5',
                DarkModePrimBtnText: '#18181b',
                LightModeSecBtn: '#e5e5e5',
                DarkModeSecBtn: '#f43f5e',
                LightModeSecBtnHover: '#e5e5e5',
                DarkModeSecBtnHover: '#e11d48',
                LightModeSecBtnText: '#e5e5e5',
                DarkModeSecBtnText: '#18181b',
                LightModeTriBtn: '#e5e5e5',
                DarkModeTriBtn: '#171717',
                LightModeTriBtnHover: '#e5e5e5',
                DarkModeTriBtnHover: '#171717',
                LightModeTriBtnText: '#e5e5e5',
                DarkModePTriBtnText: '#18181b',
                LightModeDangerBtn: '#e5e5e5',
                DarkModeDangerBtn: '#171717',
                LightModeDangerBtnHover: '#e5e5e5',
                DarkModeDangerBtnHover: '#171717',
                LightModeDangerBtnText: '#e5e5e5',
                DarkModeDangerBtnText: '#18181b',
            },
        },
    },
    plugins: [],
}
